"""Add secret question fields to users

Revision ID: 4c65ba9a360f
Revises: d5e6f7a8b9c0
Create Date: 2026-05-17 01:25:21.258368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c65ba9a360f'
down_revision = 'd5e6f7a8b9c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('secret_question', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('secret_answer_hash', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('secret_answer_hash')
        batch_op.drop_column('secret_question')

    # ### end Alembic commands ###
